PRINT " _________"
PRINT " \_     _/"
PRINT "   \   /"
PRINT "    | |"
PRINT "   /   \"
PRINT "  /     \"
PRINT " |       |"
PRINT "/---------\"
PRINT "| \-/ \-/ |"
PRINT "\---------/"
PRINT " \_______/"